# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkyWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SkyWallet
  pod 'Masonry', '~>1.1.0'
  pod 'YBUtils', '~>0.1.0'
  pod 'ReactiveObjC', '~>3.1.0'
  pod 'IQKeyboardManager'
  pod 'QRCodeReaderViewController', '~> 4.0.2'
  pod 'SVProgressHUD', '~>2.2.5'

  target 'SkyWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
